2022-09-24 16:56:47,933 INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2022-09-24 16:56:47,933 INFO [33mPress CTRL+C to quit[0m
2022-09-24 18:05:24,219 INFO Main called
2022-09-26 10:18:54,793 INFO Main called
2022-09-26 10:19:10,464 INFO Main called
2022-09-26 10:19:27,416 INFO getDeployedContracts called : ret = match_id
2022-09-26 10:19:44,948 INFO getDeployedContracts called : ret = address
2022-09-26 10:20:16,125 INFO getMatchDataWithAddress called : address = 0x18Db0ab241C5d22c966C9E0F8994f85426c52838
2022-09-26 10:21:17,256 INFO getMatchDataWithMatchId called : match_id = 390111
2022-09-26 10:27:21,974 INFO getMatchDataWithMatchId called : match_id = 390111
2022-09-26 10:27:25,929 INFO getMatchDataWithMatchId called : match_id = None
2022-09-26 10:27:25,930 ERROR Error /getMatchDataWithMatchId/ : list index out of range
2022-09-26 10:27:25,930 ERROR Exception on /getMatchDataWithMatchId/ [GET]
Traceback (most recent call last):
  File "/home/toma/.local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/toma/.local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/toma/.local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/toma/.local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/toma/Documents/decentralizeBet/CentralizeBackend_DecentralizedFootBet/FlaskAPI_DecentralizedFootBet/main.py", line 107, in getMatchDataWithMatchId
    return(json.dumps(data))
  File "/home/toma/.local/lib/python3.8/site-packages/flask/json/__init__.py", line 124, in dumps
    return app.json.dumps(obj, **kwargs)
  File "/home/toma/.local/lib/python3.8/site-packages/flask/json/provider.py", line 230, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/toma/.local/lib/python3.8/site-packages/flask/json/provider.py", line 122, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type IndexError is not JSON serializable
2022-09-26 10:27:31,325 INFO getMatchDataWithMatchId called : match_id = 390111
